# Generated by Django 2.2.10 on 2020-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jbbjhbjhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbnbnb', models.BigIntegerField()),
            ],
        ),
    ]
